[project]
name = "data-science-bootcamp-lecture-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gdown>=5.2.0",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "polars>=1.32.3",
]
